
package ctwo;

import java.sql.Connection;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class Project extends javax.swing.JFrame {

   
    public Project() {
        initComponents();
        setLocationRelativeTo(null);
         show_user();
    }
    public Connection connection;  
    public ArrayList<User1>userList()
    {
      ArrayList<User1>userList = new ArrayList<>();

         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=checkpointnotwo;selectMethod=cursor", "sa", "123456");
         
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement
                    .executeQuery("select * from Project");
            
        
             User1 user;
            
            while(resultSet.next())
         {
           user = new User1(resultSet.getInt("ProjectId"),resultSet.getInt("ServiceId"),resultSet.getInt("TeamId"),resultSet.getInt("ClientId"),resultSet.getString("ServiceFee"),resultSet.getString("OrderDate"),resultSet.getString("StartingDate"),resultSet.getString("Deadline"),resultSet.getString("CurrentStatus"));
            
            userList.add(user);

         }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
         return userList;
    
    
    
    }
      
 public void show_user()
 {
   ArrayList<User1>list = userList();
   DefaultTableModel model =(DefaultTableModel) ProjectTable.getModel();
   Object[] row = new Object[9];


   for(int i = 0;i<list.size();i++)
   {
     row[0]=list.get(i).getProjectId();
     row[1]=list.get(i).getServiceId();
     row[2]=list.get(i).getTeamId();
     row[3]=list.get(i).getClientId();
     row[4]=list.get(i).getServiceFee();
     row[5]=list.get(i).getOrderDate();
     row[6]=list.get(i).getStartingDate();
     row[7]=list.get(i).getDeadline();
     row[8]=list.get(i).getCurrentStatus();
    
     model.addRow(row);
   
   }
 
 }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProjectTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BackToMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ProjectId = new javax.swing.JTextField();
        ServiceId = new javax.swing.JTextField();
        TeamId = new javax.swing.JTextField();
        ClientId = new javax.swing.JTextField();
        ServiceFee = new javax.swing.JTextField();
        OrderDate = new javax.swing.JTextField();
        StartingDate = new javax.swing.JTextField();
        Deadline = new javax.swing.JTextField();
        CurrentStatus = new javax.swing.JTextField();
        Search = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        SearchCurrentStatus = new javax.swing.JTextField();
        Next = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1228, 780));
        setMinimumSize(new java.awt.Dimension(1228, 780));
        setPreferredSize(new java.awt.Dimension(1228, 780));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("Cleaning &");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, 40));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 250, 250));
        jLabel5.setText("Maid Service");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 190, 30));

        ProjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProjectId", "ServiceId", "TeamId", "ClientId", "ServiceFee", "OrderDate", "StartingDate", "Deadline", "CurrentStatus"
            }
        ));
        ProjectTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProjectTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProjectTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 920, 250));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Search (Enter ProjectId)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 180, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ProjectId");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ServiceId");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 110, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("TeamId");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 80, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ClientId");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 80, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ServiceFee");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("OrderDate");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("StartingDate");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Deadline");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, -1, -1));

        BackToMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackToMenu.setText("<<");
        BackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuActionPerformed(evt);
            }
        });
        jPanel1.add(BackToMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 30));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 790));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("CurrentStatus");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 110, -1));
        jPanel1.add(ProjectId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 160, -1));
        jPanel1.add(ServiceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 160, -1));
        jPanel1.add(TeamId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 160, -1));

        ClientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientIdActionPerformed(evt);
            }
        });
        jPanel1.add(ClientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 160, -1));
        jPanel1.add(ServiceFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 160, -1));

        OrderDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderDateActionPerformed(evt);
            }
        });
        jPanel1.add(OrderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 160, -1));

        StartingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartingDateActionPerformed(evt);
            }
        });
        jPanel1.add(StartingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 160, -1));

        Deadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeadlineActionPerformed(evt);
            }
        });
        jPanel1.add(Deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 160, -1));
        jPanel1.add(CurrentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 160, -1));

        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 120, -1));

        Clear.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 100, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Search(CurrentStatus)");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 170, 20));

        SearchCurrentStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCurrentStatusActionPerformed(evt);
            }
        });
        SearchCurrentStatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchCurrentStatusKeyReleased(evt);
            }
        });
        jPanel1.add(SearchCurrentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 120, -1));

        Next.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        jPanel1.add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 150, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("DUE SERVICES(Clients' Info)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientIdActionPerformed

    private void OrderDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderDateActionPerformed

    private void StartingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartingDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartingDateActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        ProjectId.setText("");
         ServiceId.setText("");
         TeamId.setText("");
         ClientId.setText("");
         ServiceFee.setText("");
         OrderDate.setText("");
         StartingDate.setText("");
         Deadline.setText("");
         CurrentStatus.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void ProjectTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProjectTableMouseClicked
         int i = ProjectTable.getSelectedRow();
        TableModel model = ProjectTable.getModel();
        ProjectId.setText(model.getValueAt(i,0).toString());
        ServiceId.setText(model.getValueAt(i,1).toString());
        TeamId.setText(model.getValueAt(i,2).toString());
        ClientId.setText(model.getValueAt(i,3).toString());
        ServiceFee.setText(model.getValueAt(i,4).toString());
        OrderDate.setText(model.getValueAt(i,5).toString());
        StartingDate.setText(model.getValueAt(i,6).toString());
        Deadline.setText(model.getValueAt(i,7).toString());
        CurrentStatus.setText(model.getValueAt(i,8).toString());
    }//GEN-LAST:event_ProjectTableMouseClicked

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        try {
           
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=checkpointnotwo;selectMethod=cursor", "sa", "123456");
            
            String sql ="Select*from  Project where  ProjectId=?";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, Search.getText());
            ResultSet rs =pst.executeQuery();
            if(rs.next())
            {
              String setProjectId = rs.getString("ProjectId");
             ProjectId.setText(setProjectId);
              String setServiceId = rs.getString("ServiceId");
              ServiceId.setText(setServiceId);
               String setTeamId= rs.getString("TeamId");
             TeamId.setText(setTeamId);
               String setClientId= rs.getString("ClientId");
             ClientId.setText(setClientId);
             String setServiceFee= rs.getString("ServiceFee");
             ServiceFee.setText(setServiceFee);
             String setOrderDate= rs.getString("OrderDate");
             OrderDate.setText(setOrderDate);
             String setStartingDate= rs.getString("StartingDate");
             StartingDate.setText(setStartingDate);
             String setDeadline= rs.getString("Deadline");
             Deadline.setText(setDeadline);
             String setCurrentStatus= rs.getString("CurrentStatus");
             CurrentStatus.setText(setCurrentStatus);
              
            
            }
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         
         }
    }//GEN-LAST:event_SearchKeyReleased

    private void BackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuActionPerformed
         menu as=new menu();
         as.setVisible(true);
         new Project().setVisible(false);
         dispose();
    }//GEN-LAST:event_BackToMenuActionPerformed

    private void SearchCurrentStatusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchCurrentStatusKeyReleased
       try {
           
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=checkpointnotwo;selectMethod=cursor", "sa", "123456");
            
            String sql ="Select*from  Project where  CurrentStatus like ?";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, SearchCurrentStatus.getText()+"%");
            
            ResultSet rs =pst.executeQuery();
            if(rs.next())
            {
              String setProjectId = rs.getString("ProjectId");
             ProjectId.setText(setProjectId);
              String setServiceId = rs.getString("ServiceId");
              ServiceId.setText(setServiceId);
               String setTeamId= rs.getString("TeamId");
             TeamId.setText(setTeamId);
               String setClientId= rs.getString("ClientId");
             ClientId.setText(setClientId);
             String setServiceFee= rs.getString("ServiceFee");
             ServiceFee.setText(setServiceFee);
             String setOrderDate= rs.getString("OrderDate");
             OrderDate.setText(setOrderDate);
             String setStartingDate= rs.getString("StartingDate");
             StartingDate.setText(setStartingDate);
             String setDeadline= rs.getString("Deadline");
             Deadline.setText(setDeadline);
             String setCurrentStatus= rs.getString("CurrentStatus");
             CurrentStatus.setText(setCurrentStatus);
              
            
            }
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         
         }
    }//GEN-LAST:event_SearchCurrentStatusKeyReleased

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        ProjectandService as=new ProjectandService();
         as.setVisible(true);
         new Project().setVisible(false);
         dispose();
    }//GEN-LAST:event_NextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DueServiceClients as=new DueServiceClients();
         as.setVisible(true);
         new Project ().setVisible(false);
         dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchCurrentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCurrentStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchCurrentStatusActionPerformed

    private void DeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeadlineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenu;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField ClientId;
    private javax.swing.JTextField CurrentStatus;
    private javax.swing.JTextField Deadline;
    private javax.swing.JButton Next;
    private javax.swing.JTextField OrderDate;
    private javax.swing.JTextField ProjectId;
    private javax.swing.JTable ProjectTable;
    private javax.swing.JTextField Search;
    private javax.swing.JTextField SearchCurrentStatus;
    private javax.swing.JTextField ServiceFee;
    private javax.swing.JTextField ServiceId;
    private javax.swing.JTextField StartingDate;
    private javax.swing.JTextField TeamId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
